version: '3.9'

services:
  fastapi:
    build: api
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: api
    volumes:
      - ./api:/api
    environment:
      - DATABASE_URL=mariadb+pymysql://leonardocarvalho:bGVvbmFyZG9j@jobs.visie.com.br:3306/leonardocarvalho
    working_dir: /api
    command: ./run.sh
    ports:
      - 8000:8000
  front:
    image: node:14.19.2-buster-slim
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: front
    environment:
      - TZ=America/Sao_Paulo
      - VUE_APP_API_URL=http://localhost:8000
    volumes:
      - ./front:/front
    working_dir: /front
    command: ./run.sh
    ports:
      - 8080:8080

